#!/bin/sh

#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

find Sources -name '*.gyb' | \
    while read file; do \
        gyb --line-directive '' -o "${file%.gyb}" "$file"; \
    done
