#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package_tests:
    name: Package ${{ matrix.platform.name }} (${{ matrix.config }})
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@lukas/rework
    strategy:
      matrix:
        config: [Debug, Release]
        platform:
          - name: iOS
            destination: 'platform=iOS Simulator,name=iPhone 16 Pro'
          - name: macOS
            destination: 'platform=macOS,arch=arm64'
          - name: watchOS
            destination: 'platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)'
          - name: visionOS
            destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      fail-fast: false
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziHealthKit-Package
      destination: ${{ matrix.platform.destination }}
      build-config: ${{ matrix.config }}
      artifactname: ${{ format('SpeziHealthKit-{0}-{1}.xcresult', matrix.platform.name, matrix.config) }}
  ui_tests:
    name: UI Tests ${{ matrix.platform.name }} (${{ matrix.config }})
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@lukas/rework
    strategy:
      matrix:
        config: [Debug, Release]
        platform:
          - name: iOS
            destination: 'platform=iOS Simulator,name=iPhone 16 Pro'
      fail-fast: false
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      destination: ${{ matrix.platform.destination }}
      artifactname: ${{ format('TestApp-{0}-{1}.xcresult', matrix.platform.name, matrix.config) }}
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [package_tests, ui_tests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@lukas/rework
    with:
      coveragereports: SpeziHealthKit-*.xcresult TestApp-*.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
